### PR TITLE
Work around dinput8.dll not existing in System32 by using COM

### LINKED ISSUE #5: [bug] The specified module could not be found Windows 11
On windows 11 we are getting this from a few users.

[2023-05-17 22:09:45.757] [error] Error running game: Error: Command failed: "\AppData\Local\renegade_x\Binaries\Win64\UDK.exe" 69.85.89.118:6666 -UseAllAvailableCores -nomoviestartup -ini:UDKGame:DefaultPlayer.Name=Efka
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }', src\dinput8.rs:6:101

### PR DESCRIPTION
**Pull request by DrChat**
Hopefully fixes #5.

### CODE REVIEW

**Comment by SonnyX** [comment]
LGTM

**Review by SonnyX — APPROVED** [review]

**Comment by DrChat** [comment]
@SonnyX Not sure if this is still being released as part of the games.
If it is, would you be able to release it for me?

**Comment by SonnyX** [comment]
@DrChat Apparently it causes game crashes, thus @sevans045 reverted it in the SVN. (I tested it locally and I didn't have the same issue tho)

**Comment by DrChat** [comment]
Hmmm, it causes _new_ crashes or it just didn't fix the previous crash?

**Comment by DHanley218003** [comment]
I tested it by deleting dinput8.dll from my system32, which resulted in crashing.

**Comment by SonnyX** [comment]
> Hmmm, it causes _new_ crashes or it just didn't fix the previous crash?

I imagine it causes new crashes, considering how quickly it was reverted, I did not speak to her about the matter.

**Comment by DrChat** [comment]
@DHanley218003 If you delete dinput8 without re-registering another copy with COM, this will indeed fail.
You could try moving the DLL and then re-registering it or something, but the test you ran won't reflect the setup of those who don't have `dinput8.dll` in their system32 directory.

**Pull request merged**
